export const menuData =
  [
    {
      "id": 1,
      "foodName": "Provence Ratatouille",
      "price": 22.0,
      "rating": 4.6,
      "country": "France",
      "course": "Main Course",
      "type": "Vegetable Stew",
      "category": "Vegan",
      "description": "Slow-roasted zucchini, eggplant, tomato, herbs, and olive oil.",
      "imageUrl": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 2,
      "foodName": "Spanish Seafood Paella",
      "price": 39.0,
      "rating": 4.8,
      "country": "Spain",
      "course": "Main Course",
      "type": "Rice",
      "category": "Nonveg",
      "description": "Saffron rice, prawns, mussels, peppers, and smoked paprika.",
      "imageUrl": "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 3,
      "foodName": "Moroccan Couscous Royale",
      "price": 27.0,
      "rating": 4.7,
      "country": "Morocco",
      "course": "Main Course",
      "type": "Couscous",
      "category": "Vegan",
      "description": "Golden couscous, chickpeas, roasted vegetables, apricot, and harissa.",
      "imageUrl": "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 4,
      "foodName": "Shanghai Egg Fried Rice",
      "price": 19.0,
      "rating": 4.5,
      "country": "China",
      "course": "Main Course",
      "type": "Fried Rice",
      "category": "Egg",
      "description": "Wok-fried jasmine rice, egg, scallions, soy, and sesame.",
      "imageUrl": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 5,
      "foodName": "Korean Bibimbap Bowl",
      "price": 26.0,
      "rating": 4.8,
      "country": "South Korea",
      "course": "Main Course",
      "type": "Rice Bowl",
      "category": "Egg",
      "description": "Rice, vegetables, gochujang, sesame, and a soft fried egg.",
      "imageUrl": "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 6,
      "foodName": "Vietnamese Beef Pho",
      "price": 29.0,
      "rating": 4.7,
      "country": "Vietnam",
      "course": "Main Course",
      "type": "Noodle Soup",
      "category": "Nonveg",
      "description": "Clear beef broth, rice noodles, herbs, sprouts, and lime.",
      "imageUrl": "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 7,
      "foodName": "Lebanese Falafel Platter",
      "price": 23.0,
      "rating": 4.6,
      "country": "Lebanon",
      "course": "Starter",
      "type": "Platter",
      "category": "Vegan",
      "description": "Crisp falafel, hummus, tahini, pickles, tabbouleh, and pita.",
      "imageUrl": "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 8,
      "foodName": "Turkish Lamb Kebab",
      "price": 35.0,
      "rating": 4.8,
      "country": "Turkey",
      "course": "Main Course",
      "type": "Kebab",
      "category": "Nonveg",
      "description": "Chargrilled lamb, sumac onion, lavash, yogurt, and herbs.",
      "imageUrl": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 9,
      "foodName": "Delhi Samosa Chaat",
      "price": 18.0,
      "rating": 4.7,
      "country": "India",
      "course": "Starter",
      "type": "Street Food",
      "category": "Vegan",
      "description": "Spiced potato samosa, chutney, chickpeas, onion, and sev.",
      "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 10,
      "foodName": "Paneer Tikka Royale",
      "price": 25.0,
      "rating": 4.8,
      "country": "India",
      "course": "Starter",
      "type": "Tandoori",
      "category": "Veg",
      "description": "Tandoori paneer, peppers, mint chutney, and pickled onion.",
      "imageUrl": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 11,
      "foodName": "Hyderabadi Chicken Biryani",
      "price": 34.0,
      "rating": 4.9,
      "country": "India",
      "course": "Main Course",
      "type": "Biryani",
      "category": "Nonveg",
      "description": "Layered basmati rice, saffron, chicken, fried onion, and raita.",
      "imageUrl": "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 12,
      "foodName": "New York Wagyu Burger",
      "price": 38.0,
      "rating": 4.6,
      "country": "USA",
      "course": "Main Course",
      "type": "Burger",
      "category": "Nonveg",
      "description": "Wagyu patty, cheddar, onion jam, brioche, and truffle fries.",
      "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 13,
      "foodName": "Manhattan Cheesecake",
      "price": 16.0,
      "rating": 4.7,
      "country": "USA",
      "course": "Dessert",
      "type": "Dessert",
      "category": "Egg",
      "description": "Cream cheese cake, berry coulis, vanilla crumb, and cream.",
      "imageUrl": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 14,
      "foodName": "Brazilian Churrasco Steak",
      "price": 46.0,
      "rating": 4.8,
      "country": "Brazil",
      "course": "Main Course",
      "type": "Grill",
      "category": "Nonveg",
      "description": "Grilled beef, chimichurri, cassava fries, and charred lime.",
      "imageUrl": "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 15,
      "foodName": "Peruvian Citrus Ceviche",
      "price": 31.0,
      "rating": 4.8,
      "country": "Peru",
      "course": "Starter",
      "type": "Ceviche",
      "category": "Nonveg",
      "description": "Fresh fish, leche de tigre, red onion, cilantro, and corn.",
      "imageUrl": "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 16,
      "foodName": "Argentinian Ribeye",
      "price": 52.0,
      "rating": 4.9,
      "country": "Argentina",
      "course": "Main Course",
      "type": "Steak",
      "category": "Nonveg",
      "description": "Grass-fed ribeye, chimichurri, roasted potato, and garlic butter.",
      "imageUrl": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 17,
      "foodName": "Quebec Truffle Poutine",
      "price": 24.0,
      "rating": 4.5,
      "country": "Canada",
      "course": "Main Course",
      "type": "Comfort Food",
      "category": "Veg",
      "description": "Crisp fries, cheese curds, mushroom gravy, and truffle oil.",
      "imageUrl": "https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 18,
      "foodName": "London Fish and Chips",
      "price": 29.0,
      "rating": 4.6,
      "country": "United Kingdom",
      "course": "Main Course",
      "type": "Seafood",
      "category": "Nonveg",
      "description": "Beer-battered cod, minted peas, tartar sauce, and fries.",
      "imageUrl": "https://images.unsplash.com/photo-1539136788836-5699e78bfc75?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 19,
      "foodName": "German Golden Schnitzel",
      "price": 33.0,
      "rating": 4.5,
      "country": "Germany",
      "course": "Main Course",
      "type": "Schnitzel",
      "category": "Nonveg",
      "description": "Crisp veal cutlet, lemon, potato salad, and mustard cream.",
      "imageUrl": "https://images.unsplash.com/photo-1677563076282-a3191d747540?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 20,
      "foodName": "Swiss Alpine Fondue",
      "price": 30.0,
      "rating": 4.6,
      "country": "Switzerland",
      "course": "Main Course",
      "type": "Fondue",
      "category": "Veg",
      "description": "Melted gruyere, emmental, bread, potatoes, and pickles.",
      "imageUrl": "https://images.unsplash.com/photo-1754910568106-e71804067c2c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 21,
      "foodName": "Athenian Moussaka",
      "price": 32.0,
      "rating": 4.7,
      "country": "Greece",
      "course": "Main Course",
      "type": "Casserole",
      "category": "Egg",
      "description": "Eggplant, tomato lamb sauce, bechamel, herbs, and olive oil.",
      "imageUrl": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 22,
      "foodName": "Lisbon Custard Tart",
      "price": 14.0,
      "rating": 4.8,
      "country": "Portugal",
      "course": "Dessert",
      "type": "Dessert",
      "category": "Egg",
      "description": "Flaky pastry, vanilla custard, cinnamon, and caramelized top.",
      "imageUrl": "https://images.unsplash.com/photo-1671369527952-2caec36dee50?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 23,
      "foodName": "Milanese Saffron Risotto",
      "price": 34.0,
      "rating": 4.8,
      "country": "Italy",
      "course": "Main Course",
      "type": "Risotto",
      "category": "Veg",
      "description": "Carnaroli rice, saffron, parmesan, butter, and herb oil.",
      "imageUrl": "https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 24,
      "foodName": "French Duck Confit",
      "price": 45.0,
      "rating": 4.9,
      "country": "France",
      "course": "Main Course",
      "type": "Roast",
      "category": "Nonveg",
      "description": "Slow-cooked duck leg, potato pave, greens, and cherry jus.",
      "imageUrl": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 25,
      "foodName": "Tokyo Shoyu Ramen",
      "price": 27.0,
      "rating": 4.8,
      "country": "Japan",
      "course": "Main Course",
      "type": "Noodles",
      "category": "Egg",
      "description": "Soy broth, noodles, egg, nori, scallions, and bamboo shoots.",
      "imageUrl": "https://images.unsplash.com/photo-1637024696628-02cb19cc1829?q=80&w=1217&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 26,
      "foodName": "Kyoto Vegetable Tempura",
      "price": 24.0,
      "rating": 4.6,
      "country": "Japan",
      "course": "Starter",
      "type": "Tempura",
      "category": "Veg",
      "description": "Light tempura vegetables, tentsuyu, grated daikon, and salt.",
      "imageUrl": "https://images.unsplash.com/photo-1677050205809-60b00c86eda3?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 27,
      "foodName": "Malaysian Prawn Laksa",
      "price": 30.0,
      "rating": 4.7,
      "country": "Malaysia",
      "course": "Main Course",
      "type": "Noodle Soup",
      "category": "Nonveg",
      "description": "Coconut noodle soup, prawns, tofu puff, herbs, and chili oil.",
      "imageUrl": "https://images.unsplash.com/photo-1604909052743-94e838986d24?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 28,
      "foodName": "Indonesian Chicken Satay",
      "price": 26.0,
      "rating": 4.6,
      "country": "Indonesia",
      "course": "Starter",
      "type": "Skewers",
      "category": "Nonveg",
      "description": "Grilled chicken skewers, peanut sauce, cucumber, and rice cake.",
      "imageUrl": "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 29,
      "foodName": "Filipino Chicken Adobo",
      "price": 28.0,
      "rating": 4.6,
      "country": "Philippines",
      "course": "Main Course",
      "type": "Braise",
      "category": "Nonveg",
      "description": "Soy-vinegar braised chicken, garlic rice, bay leaf, and pepper.",
      "imageUrl": "https://images.unsplash.com/photo-1538974463296-4d76476ffeb2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 30,
      "foodName": "Singapore Chili Crab",
      "price": 56.0,
      "rating": 4.9,
      "country": "Singapore",
      "course": "Main Course",
      "type": "Seafood",
      "category": "Nonveg",
      "description": "Sweet crab, tomato chili sauce, scallion, and fried mantou.",
      "imageUrl": "https://images.unsplash.com/photo-1604908177453-7462950a6a3b?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 31,
      "foodName": "Sri Lankan Egg Hopper",
      "price": 21.0,
      "rating": 4.5,
      "country": "Sri Lanka",
      "course": "Main Course",
      "type": "Hopper",
      "category": "Egg",
      "description": "Crisp rice flour bowl, egg, sambol, coconut, and curry leaf.",
      "imageUrl": "https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 32,
      "foodName": "Nepali Vegetable Momos",
      "price": 20.0,
      "rating": 4.6,
      "country": "Nepal",
      "course": "Main Course",
      "type": "Dumplings",
      "category": "Veg",
      "description": "Steamed dumplings, sesame tomato chutney, herbs, and chili.",
      "imageUrl": "https://images.unsplash.com/photo-1683367420839-d6470b24ab25?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 33,
      "foodName": "Lahori Beef Nihari",
      "price": 36.0,
      "rating": 4.8,
      "country": "Pakistan",
      "course": "Main Course",
      "type": "Stew",
      "category": "Nonveg",
      "description": "Slow-braised beef, warm spices, ginger, herbs, and naan.",
      "imageUrl": "https://images.unsplash.com/photo-1708782345549-7285b1c977d6?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 34,
      "foodName": "Mexico City Street Tacos",
      "price": 25.0,
      "rating": 4.7,
      "country": "Mexico",
      "course": "Main Course",
      "type": "Tacos",
      "category": "Nonveg",
      "description": "Corn tortillas, marinated beef, onion, cilantro, and salsa verde.",
      "imageUrl": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 35,
      "foodName": "Jamaican Jerk Chicken",
      "price": 33.0,
      "rating": 4.7,
      "country": "Jamaica",
      "course": "Main Course",
      "type": "Grill",
      "category": "Nonveg",
      "description": "Allspice-marinated chicken, rice, peas, pineapple, and lime.",
      "imageUrl": "https://images.unsplash.com/photo-1632852576480-c10a8e19496a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 36,
      "foodName": "Havana Cubano Press",
      "price": 24.0,
      "rating": 4.5,
      "country": "Cuba",
      "course": "Main Course",
      "type": "Sandwich",
      "category": "Nonveg",
      "description": "Roast pork, ham, swiss, pickles, mustard, and pressed bread.",
      "imageUrl": "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 37,
      "foodName": "Ethiopian Injera Feast",
      "price": 29.0,
      "rating": 4.7,
      "country": "Ethiopia",
      "course": "Starter",
      "type": "Platter",
      "category": "Vegan",
      "description": "Injera, lentil stew, spiced vegetables, berbere, and herbs.",
      "imageUrl": "https://images.unsplash.com/photo-1640116345144-8fca02e277b8?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 38,
      "foodName": "Egyptian Koshari",
      "price": 22.0,
      "rating": 4.6,
      "country": "Egypt",
      "course": "Main Course",
      "type": "Bowl",
      "category": "Vegan",
      "description": "Lentils, rice, pasta, tomato sauce, fried onions, and chickpeas.",
      "imageUrl": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 39,
      "foodName": "South African Bobotie",
      "price": 31.0,
      "rating": 4.5,
      "country": "South Africa",
      "course": "Main Course",
      "type": "Baked Dish",
      "category": "Egg",
      "description": "Spiced minced beef, custard topping, chutney, and yellow rice.",
      "imageUrl": "https://images.unsplash.com/photo-1576402187878-974f70c890a5?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 40,
      "foodName": "Australian Lamb Rack",
      "price": 49.0,
      "rating": 4.8,
      "country": "Australia",
      "course": "Main Course",
      "type": "Roast",
      "category": "Nonveg",
      "description": "Herb-crusted lamb, pea puree, potato gratin, and rosemary jus.",
      "imageUrl": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 41,
      "foodName": "New Zealand Mussels",
      "price": 34.0,
      "rating": 4.7,
      "country": "New Zealand",
      "course": "Main Course",
      "type": "Seafood",
      "category": "Nonveg",
      "description": "Green-lipped mussels, white wine, garlic, parsley, and lemon.",
      "imageUrl": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 42,
      "foodName": "Swedish Meatballs",
      "price": 28.0,
      "rating": 4.5,
      "country": "Sweden",
      "course": "Main Course",
      "type": "Meatballs",
      "category": "Nonveg",
      "description": "Beef meatballs, cream sauce, lingonberry, and mashed potato.",
      "imageUrl": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 43,
      "foodName": "Norwegian Salmon Gravlax",
      "price": 30.0,
      "rating": 4.7,
      "country": "Norway",
      "course": "Main Course",
      "type": "Seafood",
      "category": "Nonveg",
      "description": "Cured salmon, dill, mustard sauce, rye crisp, and capers.",
      "imageUrl": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
      "id": 44,
      "foodName": "Polish Potato Pierogi",
      "price": 23.0,
      "rating": 4.6,
      "country": "Poland",
      "course": "Main Course",
      "type": "Dumplings",
      "category": "Veg",
      "description": "Dumplings, potato cheese filling, sour cream, and onion butter.",
      "imageUrl": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 45,
      "foodName": "Russian Blini Caviar",
      "price": 42.0,
      "rating": 4.8,
      "country": "Russia",
      "course": "Starter",
      "type": "Canape",
      "category": "Egg",
      "description": "Mini blini, creme fraiche, caviar, chive, and lemon zest.",
      "imageUrl": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 46,
      "foodName": "Hungarian Beef Goulash",
      "price": 33.0,
      "rating": 4.6,
      "country": "Hungary",
      "course": "Main Course",
      "type": "Stew",
      "category": "Nonveg",
      "description": "Paprika beef stew, peppers, potato, sour cream, and herbs.",
      "imageUrl": "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 47,
      "foodName": "Czech Herb Dumplings",
      "price": 20.0,
      "rating": 4.4,
      "country": "Czech Republic",
      "course": "Main Course",
      "type": "Dumplings",
      "category": "Veg",
      "description": "Bread dumplings, mushroom sauce, parsley, and roasted onions.",
      "imageUrl": "https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 48,
      "foodName": "Vienna Sachertorte",
      "price": 17.0,
      "rating": 4.7,
      "country": "Austria",
      "course": "Dessert",
      "type": "Dessert",
      "category": "Egg",
      "description": "Chocolate cake, apricot glaze, ganache, and whipped cream.",
      "imageUrl": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 49,
      "foodName": "Belgian Golden Waffles",
      "price": 18.0,
      "rating": 4.6,
      "country": "Belgium",
      "course": "Dessert",
      "type": "Dessert",
      "category": "Egg",
      "description": "Crisp waffles, vanilla cream, berries, and dark chocolate.",
      "imageUrl": "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 50,
      "foodName": "Dutch Mini Pancakes",
      "price": 16.0,
      "rating": 4.5,
      "country": "Netherlands",
      "course": "Dessert",
      "type": "Dessert",
      "category": "Egg",
      "description": "Poffertjes, powdered sugar, berry sauce, and whipped butter.",
      "imageUrl": "https://images.unsplash.com/photo-1653228090868-f2d8308cbf07?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
  ]
